[package]
name = "crypto_speed"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
rand_core = "0.9.3"
rencfs = "0.14.11"
shush-rs = "0.1.11"
tokio = { version = "1.36", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }